/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// AddSecuritySchemeLevelsRequestBean
    /// </summary>
    [DataContract(Name = "AddSecuritySchemeLevelsRequestBean")]
    public partial class AddSecuritySchemeLevelsRequestBean : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddSecuritySchemeLevelsRequestBean" /> class.
        /// </summary>
        /// <param name="levels">The list of scheme levels which should be added to the security scheme..</param>
        public AddSecuritySchemeLevelsRequestBean(List<SecuritySchemeLevelBean> levels = default(List<SecuritySchemeLevelBean>))
        {
            this.Levels = levels;
        }

        /// <summary>
        /// The list of scheme levels which should be added to the security scheme.
        /// </summary>
        /// <value>The list of scheme levels which should be added to the security scheme.</value>
        [DataMember(Name = "levels", EmitDefaultValue = false)]
        public List<SecuritySchemeLevelBean> Levels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddSecuritySchemeLevelsRequestBean {\n");
            sb.Append("  Levels: ").Append(Levels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
