/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Details for changing owners of shareable entities
    /// </summary>
    [DataContract(Name = "BulkChangeOwnerDetails")]
    public partial class BulkChangeOwnerDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkChangeOwnerDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkChangeOwnerDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkChangeOwnerDetails" /> class.
        /// </summary>
        /// <param name="autofixName">Whether the name is fixed automatically if it&#39;s duplicated after changing owner. (required).</param>
        /// <param name="newOwner">The account id of the new owner. (required).</param>
        public BulkChangeOwnerDetails(bool autofixName = default(bool), string newOwner = default(string))
        {
            this.AutofixName = autofixName;
            // to ensure "newOwner" is required (not null)
            if (newOwner == null)
            {
                throw new ArgumentNullException("newOwner is a required property for BulkChangeOwnerDetails and cannot be null");
            }
            this.NewOwner = newOwner;
        }

        /// <summary>
        /// Whether the name is fixed automatically if it&#39;s duplicated after changing owner.
        /// </summary>
        /// <value>Whether the name is fixed automatically if it&#39;s duplicated after changing owner.</value>
        [DataMember(Name = "autofixName", IsRequired = true, EmitDefaultValue = true)]
        public bool AutofixName { get; set; }

        /// <summary>
        /// The account id of the new owner.
        /// </summary>
        /// <value>The account id of the new owner.</value>
        [DataMember(Name = "newOwner", IsRequired = true, EmitDefaultValue = true)]
        public string NewOwner { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkChangeOwnerDetails {\n");
            sb.Append("  AutofixName: ").Append(AutofixName).Append("\n");
            sb.Append("  NewOwner: ").Append(NewOwner).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
