/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Errors of bulk edit action.
    /// </summary>
    [DataContract(Name = "BulkEditActionError")]
    public partial class BulkEditActionError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkEditActionError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkEditActionError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkEditActionError" /> class.
        /// </summary>
        /// <param name="errorMessages">The error messages. (required).</param>
        /// <param name="errors">The errors. (required).</param>
        public BulkEditActionError(List<string> errorMessages = default(List<string>), Dictionary<string, string> errors = default(Dictionary<string, string>))
        {
            // to ensure "errorMessages" is required (not null)
            if (errorMessages == null)
            {
                throw new ArgumentNullException("errorMessages is a required property for BulkEditActionError and cannot be null");
            }
            this.ErrorMessages = errorMessages;
            // to ensure "errors" is required (not null)
            if (errors == null)
            {
                throw new ArgumentNullException("errors is a required property for BulkEditActionError and cannot be null");
            }
            this.Errors = errors;
        }

        /// <summary>
        /// The error messages.
        /// </summary>
        /// <value>The error messages.</value>
        [DataMember(Name = "errorMessages", IsRequired = true, EmitDefaultValue = true)]
        public List<string> ErrorMessages { get; set; }

        /// <summary>
        /// The errors.
        /// </summary>
        /// <value>The errors.</value>
        [DataMember(Name = "errors", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkEditActionError {\n");
            sb.Append("  ErrorMessages: ").Append(ErrorMessages).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
