/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Details of an issue type scheme and its associated issue types.
    /// </summary>
    [DataContract(Name = "IssueTypeSchemeDetails")]
    public partial class IssueTypeSchemeDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueTypeSchemeDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IssueTypeSchemeDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueTypeSchemeDetails" /> class.
        /// </summary>
        /// <param name="defaultIssueTypeId">The ID of the default issue type of the issue type scheme. This ID must be included in &#x60;issueTypeIds&#x60;..</param>
        /// <param name="description">The description of the issue type scheme. The maximum length is 4000 characters..</param>
        /// <param name="issueTypeIds">The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required. (required).</param>
        /// <param name="name">The name of the issue type scheme. The name must be unique. The maximum length is 255 characters. (required).</param>
        public IssueTypeSchemeDetails(string defaultIssueTypeId = default(string), string description = default(string), List<string> issueTypeIds = default(List<string>), string name = default(string))
        {
            // to ensure "issueTypeIds" is required (not null)
            if (issueTypeIds == null)
            {
                throw new ArgumentNullException("issueTypeIds is a required property for IssueTypeSchemeDetails and cannot be null");
            }
            this.IssueTypeIds = issueTypeIds;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for IssueTypeSchemeDetails and cannot be null");
            }
            this.Name = name;
            this.DefaultIssueTypeId = defaultIssueTypeId;
            this.Description = description;
        }

        /// <summary>
        /// The ID of the default issue type of the issue type scheme. This ID must be included in &#x60;issueTypeIds&#x60;.
        /// </summary>
        /// <value>The ID of the default issue type of the issue type scheme. This ID must be included in &#x60;issueTypeIds&#x60;.</value>
        [DataMember(Name = "defaultIssueTypeId", EmitDefaultValue = false)]
        public string DefaultIssueTypeId { get; set; }

        /// <summary>
        /// The description of the issue type scheme. The maximum length is 4000 characters.
        /// </summary>
        /// <value>The description of the issue type scheme. The maximum length is 4000 characters.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required.
        /// </summary>
        /// <value>The list of issue types IDs of the issue type scheme. At least one standard issue type ID is required.</value>
        [DataMember(Name = "issueTypeIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> IssueTypeIds { get; set; }

        /// <summary>
        /// The name of the issue type scheme. The name must be unique. The maximum length is 255 characters.
        /// </summary>
        /// <value>The name of the issue type scheme. The name must be unique. The maximum length is 255 characters.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssueTypeSchemeDetails {\n");
            sb.Append("  DefaultIssueTypeId: ").Append(DefaultIssueTypeId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IssueTypeIds: ").Append(IssueTypeIds).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
