/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// An operand that can be part of a list operand.
    /// </summary>
    [JsonConverter(typeof(JqlQueryUnitaryOperandJsonConverter))]
    [DataContract(Name = "JqlQueryUnitaryOperand")]
    public partial class JqlQueryUnitaryOperand : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JqlQueryUnitaryOperand" /> class
        /// with the <see cref="ValueOperand" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ValueOperand.</param>
        public JqlQueryUnitaryOperand(ValueOperand actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JqlQueryUnitaryOperand" /> class
        /// with the <see cref="FunctionOperand" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FunctionOperand.</param>
        public JqlQueryUnitaryOperand(FunctionOperand actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JqlQueryUnitaryOperand" /> class
        /// with the <see cref="KeywordOperand" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of KeywordOperand.</param>
        public JqlQueryUnitaryOperand(KeywordOperand actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(FunctionOperand))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(KeywordOperand))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ValueOperand))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: FunctionOperand, KeywordOperand, ValueOperand");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ValueOperand`. If the actual instance is not `ValueOperand`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ValueOperand</returns>
        public ValueOperand GetValueOperand()
        {
            return (ValueOperand)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `FunctionOperand`. If the actual instance is not `FunctionOperand`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FunctionOperand</returns>
        public FunctionOperand GetFunctionOperand()
        {
            return (FunctionOperand)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `KeywordOperand`. If the actual instance is not `KeywordOperand`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of KeywordOperand</returns>
        public KeywordOperand GetKeywordOperand()
        {
            return (KeywordOperand)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JqlQueryUnitaryOperand {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, JqlQueryUnitaryOperand.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of JqlQueryUnitaryOperand
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of JqlQueryUnitaryOperand</returns>
        public static JqlQueryUnitaryOperand FromJson(string jsonString)
        {
            JqlQueryUnitaryOperand newJqlQueryUnitaryOperand = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newJqlQueryUnitaryOperand;
            }

            try
            {
                newJqlQueryUnitaryOperand = new JqlQueryUnitaryOperand(JsonConvert.DeserializeObject<FunctionOperand>(jsonString, JqlQueryUnitaryOperand.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newJqlQueryUnitaryOperand;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FunctionOperand: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newJqlQueryUnitaryOperand = new JqlQueryUnitaryOperand(JsonConvert.DeserializeObject<KeywordOperand>(jsonString, JqlQueryUnitaryOperand.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newJqlQueryUnitaryOperand;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into KeywordOperand: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newJqlQueryUnitaryOperand = new JqlQueryUnitaryOperand(JsonConvert.DeserializeObject<ValueOperand>(jsonString, JqlQueryUnitaryOperand.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newJqlQueryUnitaryOperand;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ValueOperand: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for JqlQueryUnitaryOperand
    /// </summary>
    public class JqlQueryUnitaryOperandJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(JqlQueryUnitaryOperand).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return JqlQueryUnitaryOperand.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return JqlQueryUnitaryOperand.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
