/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// JQL queries that contained users that could not be found
    /// </summary>
    [DataContract(Name = "JQLQueryWithUnknownUsers")]
    public partial class JQLQueryWithUnknownUsers : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JQLQueryWithUnknownUsers" /> class.
        /// </summary>
        /// <param name="convertedQuery">The converted query, with accountIDs instead of user identifiers, or &#39;unknown&#39; for users that could not be found.</param>
        /// <param name="originalQuery">The original query, for reference.</param>
        public JQLQueryWithUnknownUsers(string convertedQuery = default(string), string originalQuery = default(string))
        {
            this.ConvertedQuery = convertedQuery;
            this.OriginalQuery = originalQuery;
        }

        /// <summary>
        /// The converted query, with accountIDs instead of user identifiers, or &#39;unknown&#39; for users that could not be found
        /// </summary>
        /// <value>The converted query, with accountIDs instead of user identifiers, or &#39;unknown&#39; for users that could not be found</value>
        [DataMember(Name = "convertedQuery", EmitDefaultValue = false)]
        public string ConvertedQuery { get; set; }

        /// <summary>
        /// The original query, for reference
        /// </summary>
        /// <value>The original query, for reference</value>
        [DataMember(Name = "originalQuery", EmitDefaultValue = false)]
        public string OriginalQuery { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JQLQueryWithUnknownUsers {\n");
            sb.Append("  ConvertedQuery: ").Append(ConvertedQuery).Append("\n");
            sb.Append("  OriginalQuery: ").Append(OriginalQuery).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
