/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Details of a notification scheme event.
    /// </summary>
    [DataContract(Name = "NotificationSchemeEventDetails")]
    public partial class NotificationSchemeEventDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationSchemeEventDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NotificationSchemeEventDetails()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationSchemeEventDetails" /> class.
        /// </summary>
        /// <param name="varEvent">The ID of the event. (required).</param>
        /// <param name="notifications">The list of notifications mapped to a specified event. (required).</param>
        public NotificationSchemeEventDetails(NotificationSchemeEventTypeId varEvent = default(NotificationSchemeEventTypeId), List<NotificationSchemeNotificationDetails> notifications = default(List<NotificationSchemeNotificationDetails>))
        {
            // to ensure "varEvent" is required (not null)
            if (varEvent == null)
            {
                throw new ArgumentNullException("varEvent is a required property for NotificationSchemeEventDetails and cannot be null");
            }
            this.VarEvent = varEvent;
            // to ensure "notifications" is required (not null)
            if (notifications == null)
            {
                throw new ArgumentNullException("notifications is a required property for NotificationSchemeEventDetails and cannot be null");
            }
            this.Notifications = notifications;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The ID of the event.
        /// </summary>
        /// <value>The ID of the event.</value>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = true)]
        public NotificationSchemeEventTypeId VarEvent { get; set; }

        /// <summary>
        /// The list of notifications mapped to a specified event.
        /// </summary>
        /// <value>The list of notifications mapped to a specified event.</value>
        [DataMember(Name = "notifications", IsRequired = true, EmitDefaultValue = true)]
        public List<NotificationSchemeNotificationDetails> Notifications { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationSchemeEventDetails {\n");
            sb.Append("  VarEvent: ").Append(VarEvent).Append("\n");
            sb.Append("  Notifications: ").Append(Notifications).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
