/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Details for permissions of shareable entities
    /// </summary>
    [DataContract(Name = "PermissionDetails")]
    public partial class PermissionDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PermissionDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionDetails" /> class.
        /// </summary>
        /// <param name="editPermissions">The edit permissions for the shareable entities. (required).</param>
        /// <param name="sharePermissions">The share permissions for the shareable entities. (required).</param>
        public PermissionDetails(List<SharePermission> editPermissions = default(List<SharePermission>), List<SharePermission> sharePermissions = default(List<SharePermission>))
        {
            // to ensure "editPermissions" is required (not null)
            if (editPermissions == null)
            {
                throw new ArgumentNullException("editPermissions is a required property for PermissionDetails and cannot be null");
            }
            this.EditPermissions = editPermissions;
            // to ensure "sharePermissions" is required (not null)
            if (sharePermissions == null)
            {
                throw new ArgumentNullException("sharePermissions is a required property for PermissionDetails and cannot be null");
            }
            this.SharePermissions = sharePermissions;
        }

        /// <summary>
        /// The edit permissions for the shareable entities.
        /// </summary>
        /// <value>The edit permissions for the shareable entities.</value>
        [DataMember(Name = "editPermissions", IsRequired = true, EmitDefaultValue = true)]
        public List<SharePermission> EditPermissions { get; set; }

        /// <summary>
        /// The share permissions for the shareable entities.
        /// </summary>
        /// <value>The share permissions for the shareable entities.</value>
        [DataMember(Name = "sharePermissions", IsRequired = true, EmitDefaultValue = true)]
        public List<SharePermission> SharePermissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PermissionDetails {\n");
            sb.Append("  EditPermissions: ").Append(EditPermissions).Append("\n");
            sb.Append("  SharePermissions: ").Append(SharePermissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
