/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// A list of project IDs.
    /// </summary>
    [DataContract(Name = "ProjectIds")]
    public partial class ProjectIds : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectIds" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProjectIds() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectIds" /> class.
        /// </summary>
        /// <param name="varProjectIds">The IDs of projects. (required).</param>
        public ProjectIds(List<string> varProjectIds = default(List<string>))
        {
            // to ensure "varProjectIds" is required (not null)
            if (varProjectIds == null)
            {
                throw new ArgumentNullException("varProjectIds is a required property for ProjectIds and cannot be null");
            }
            this.VarProjectIds = varProjectIds;
        }

        /// <summary>
        /// The IDs of projects.
        /// </summary>
        /// <value>The IDs of projects.</value>
        [DataMember(Name = "projectIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> VarProjectIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectIds {\n");
            sb.Append("  VarProjectIds: ").Append(VarProjectIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
