/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// The list of required status mappings by issue type.
    /// </summary>
    [DataContract(Name = "RequiredMappingByIssueType")]
    public partial class RequiredMappingByIssueType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequiredMappingByIssueType" /> class.
        /// </summary>
        /// <param name="issueTypeId">The ID of the issue type..</param>
        /// <param name="statusIds">The status IDs requiring mapping..</param>
        public RequiredMappingByIssueType(string issueTypeId = default(string), List<string> statusIds = default(List<string>))
        {
            this.IssueTypeId = issueTypeId;
            this.StatusIds = statusIds;
        }

        /// <summary>
        /// The ID of the issue type.
        /// </summary>
        /// <value>The ID of the issue type.</value>
        [DataMember(Name = "issueTypeId", EmitDefaultValue = false)]
        public string IssueTypeId { get; set; }

        /// <summary>
        /// The status IDs requiring mapping.
        /// </summary>
        /// <value>The status IDs requiring mapping.</value>
        [DataMember(Name = "statusIds", EmitDefaultValue = false)]
        public List<string> StatusIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequiredMappingByIssueType {\n");
            sb.Append("  IssueTypeId: ").Append(IssueTypeId).Append("\n");
            sb.Append("  StatusIds: ").Append(StatusIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
