/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// Various counts of issues within a version.
    /// </summary>
    [DataContract(Name = "VersionIssueCounts")]
    public partial class VersionIssueCounts : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionIssueCounts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public VersionIssueCounts()
        {
        }

        /// <summary>
        /// List of custom fields using the version.
        /// </summary>
        /// <value>List of custom fields using the version.</value>
        [DataMember(Name = "customFieldUsage", EmitDefaultValue = false)]
        public List<VersionUsageInCustomField> CustomFieldUsage { get; private set; }

        /// <summary>
        /// Returns false as CustomFieldUsage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCustomFieldUsage()
        {
            return false;
        }
        /// <summary>
        /// Count of issues where a version custom field is set to the version.
        /// </summary>
        /// <value>Count of issues where a version custom field is set to the version.</value>
        [DataMember(Name = "issueCountWithCustomFieldsShowingVersion", EmitDefaultValue = false)]
        public long IssueCountWithCustomFieldsShowingVersion { get; private set; }

        /// <summary>
        /// Returns false as IssueCountWithCustomFieldsShowingVersion should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIssueCountWithCustomFieldsShowingVersion()
        {
            return false;
        }
        /// <summary>
        /// Count of issues where the &#x60;affectedVersion&#x60; is set to the version.
        /// </summary>
        /// <value>Count of issues where the &#x60;affectedVersion&#x60; is set to the version.</value>
        [DataMember(Name = "issuesAffectedCount", EmitDefaultValue = false)]
        public long IssuesAffectedCount { get; private set; }

        /// <summary>
        /// Returns false as IssuesAffectedCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIssuesAffectedCount()
        {
            return false;
        }
        /// <summary>
        /// Count of issues where the &#x60;fixVersion&#x60; is set to the version.
        /// </summary>
        /// <value>Count of issues where the &#x60;fixVersion&#x60; is set to the version.</value>
        [DataMember(Name = "issuesFixedCount", EmitDefaultValue = false)]
        public long IssuesFixedCount { get; private set; }

        /// <summary>
        /// Returns false as IssuesFixedCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIssuesFixedCount()
        {
            return false;
        }
        /// <summary>
        /// The URL of these count details.
        /// </summary>
        /// <value>The URL of these count details.</value>
        [DataMember(Name = "self", EmitDefaultValue = false)]
        public string Self { get; private set; }

        /// <summary>
        /// Returns false as Self should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSelf()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VersionIssueCounts {\n");
            sb.Append("  CustomFieldUsage: ").Append(CustomFieldUsage).Append("\n");
            sb.Append("  IssueCountWithCustomFieldsShowingVersion: ").Append(IssueCountWithCustomFieldsShowingVersion).Append("\n");
            sb.Append("  IssuesAffectedCount: ").Append(IssuesAffectedCount).Append("\n");
            sb.Append("  IssuesFixedCount: ").Append(IssuesFixedCount).Append("\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
