/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// The x and y location of the status in the workflow.
    /// </summary>
    [DataContract(Name = "WorkflowStatusLayout")]
    public partial class WorkflowStatusLayout : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStatusLayout" /> class.
        /// </summary>
        /// <param name="x">The x axis location..</param>
        /// <param name="y">The y axis location..</param>
        public WorkflowStatusLayout(double? x = default(double?), double? y = default(double?))
        {
            this.X = x;
            this.Y = y;
        }

        /// <summary>
        /// The x axis location.
        /// </summary>
        /// <value>The x axis location.</value>
        [DataMember(Name = "x", EmitDefaultValue = true)]
        public double? X { get; set; }

        /// <summary>
        /// The y axis location.
        /// </summary>
        /// <value>The y axis location.</value>
        [DataMember(Name = "y", EmitDefaultValue = true)]
        public double? Y { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowStatusLayout {\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
