/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// The list of status mappings.
    /// </summary>
    [DataContract(Name = "WorkflowAssociationStatusMapping")]
    public partial class WorkflowAssociationStatusMapping : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowAssociationStatusMapping" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowAssociationStatusMapping() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowAssociationStatusMapping" /> class.
        /// </summary>
        /// <param name="newStatusId">The ID of the status in the new workflow. (required).</param>
        /// <param name="oldStatusId">The ID of the status in the old workflow that isn&#39;t present in the new workflow. (required).</param>
        public WorkflowAssociationStatusMapping(string newStatusId = default(string), string oldStatusId = default(string))
        {
            // to ensure "newStatusId" is required (not null)
            if (newStatusId == null)
            {
                throw new ArgumentNullException("newStatusId is a required property for WorkflowAssociationStatusMapping and cannot be null");
            }
            this.NewStatusId = newStatusId;
            // to ensure "oldStatusId" is required (not null)
            if (oldStatusId == null)
            {
                throw new ArgumentNullException("oldStatusId is a required property for WorkflowAssociationStatusMapping and cannot be null");
            }
            this.OldStatusId = oldStatusId;
        }

        /// <summary>
        /// The ID of the status in the new workflow.
        /// </summary>
        /// <value>The ID of the status in the new workflow.</value>
        [DataMember(Name = "newStatusId", IsRequired = true, EmitDefaultValue = true)]
        public string NewStatusId { get; set; }

        /// <summary>
        /// The ID of the status in the old workflow that isn&#39;t present in the new workflow.
        /// </summary>
        /// <value>The ID of the status in the old workflow that isn&#39;t present in the new workflow.</value>
        [DataMember(Name = "oldStatusId", IsRequired = true, EmitDefaultValue = true)]
        public string OldStatusId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowAssociationStatusMapping {\n");
            sb.Append("  NewStatusId: ").Append(NewStatusId).Append("\n");
            sb.Append("  OldStatusId: ").Append(OldStatusId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
