/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-9aad01a33a3dae75a5b6aedf98c77d2cbd2f865d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Projects.JiraPlatformApi.Client.OpenAPIDateConverter;

namespace Projects.JiraPlatformApi.Model
{
    /// <summary>
    /// The request payload to get the required mappings for updating a workflow scheme.
    /// </summary>
    [DataContract(Name = "WorkflowSchemeUpdateRequiredMappingsRequest")]
    public partial class WorkflowSchemeUpdateRequiredMappingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSchemeUpdateRequiredMappingsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowSchemeUpdateRequiredMappingsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowSchemeUpdateRequiredMappingsRequest" /> class.
        /// </summary>
        /// <param name="defaultWorkflowId">The ID of the new default workflow for this workflow scheme. Only used in global-scoped workflow schemes. If it isn&#39;t specified, is set to *Jira Workflow (jira)*..</param>
        /// <param name="id">The ID of the workflow scheme. (required).</param>
        /// <param name="workflowsForIssueTypes">The new workflow to issue type mappings for this workflow scheme. (required).</param>
        public WorkflowSchemeUpdateRequiredMappingsRequest(string defaultWorkflowId = default(string), string id = default(string), List<WorkflowSchemeAssociation> workflowsForIssueTypes = default(List<WorkflowSchemeAssociation>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WorkflowSchemeUpdateRequiredMappingsRequest and cannot be null");
            }
            this.Id = id;
            // to ensure "workflowsForIssueTypes" is required (not null)
            if (workflowsForIssueTypes == null)
            {
                throw new ArgumentNullException("workflowsForIssueTypes is a required property for WorkflowSchemeUpdateRequiredMappingsRequest and cannot be null");
            }
            this.WorkflowsForIssueTypes = workflowsForIssueTypes;
            this.DefaultWorkflowId = defaultWorkflowId;
        }

        /// <summary>
        /// The ID of the new default workflow for this workflow scheme. Only used in global-scoped workflow schemes. If it isn&#39;t specified, is set to *Jira Workflow (jira)*.
        /// </summary>
        /// <value>The ID of the new default workflow for this workflow scheme. Only used in global-scoped workflow schemes. If it isn&#39;t specified, is set to *Jira Workflow (jira)*.</value>
        [DataMember(Name = "defaultWorkflowId", EmitDefaultValue = true)]
        public string DefaultWorkflowId { get; set; }

        /// <summary>
        /// The ID of the workflow scheme.
        /// </summary>
        /// <value>The ID of the workflow scheme.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The new workflow to issue type mappings for this workflow scheme.
        /// </summary>
        /// <value>The new workflow to issue type mappings for this workflow scheme.</value>
        [DataMember(Name = "workflowsForIssueTypes", IsRequired = true, EmitDefaultValue = true)]
        public List<WorkflowSchemeAssociation> WorkflowsForIssueTypes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowSchemeUpdateRequiredMappingsRequest {\n");
            sb.Append("  DefaultWorkflowId: ").Append(DefaultWorkflowId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  WorkflowsForIssueTypes: ").Append(WorkflowsForIssueTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
