name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NXCACHE_MINIO_URL: ${{ secrets.NXCACHE_MINIO_URL }}
      NXCACHE_MINIO_SECRET_KEY: ${{ secrets.NXCACHE_MINIO_SECRET_KEY }}
      NXCACHE_MINIO_ACCESS_KEY: ${{ secrets.NXCACHE_MINIO_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --immutable

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 -c=production
      - run: npx nx affected -t build --parallel=3
#      - uses: actions/upload-artifact@v3
#        name: upload nx cache for debugging
#        if: always()
#        with:
#          name: nx-cache
#          path: ./node_modules/.cache/nx
